### ISSUE TITLE
регистрация

### ISSUE THREAD

**Issue by FuriousCoder** [learnpython/team-beta#1]
сделать шаблон и представление

**Comment by kobzar** [comment]
Идея такая - пользователь жмакает на кнопку регистрации, которая перенаправляет его на флетпейдж с индексом /register/ (который в свою очередь встраивается в главный шаблон - то есть шапка заново не грузиться - это можешь уже посмотреть) - потом юзер забивает поля - и жмакает кнопку Зарегистрировать - которая отправляет уже методом ГЕТ (пока идет отладка надо юзать ГЕТ что бы было видно что мы передали) отправляет данные на линк resister_user который мы уже обрабатываем через urls.py и перенаправляем в views.py
и выводим данные опят же зависимым шаблоном от index.html что бы не перегружать всю страницу. Итого - на сейчас нужно немного переделать страницу регистрации, а именно - нужно сделать так что бы при выборе типа пользователя менялось количество полей для ввода, если юзер 4 поля если контрагент 8 полей (ну не суть важно) и что бы по нажатию кнопки это все передавалось вместе со значением типа пользователя, потому что потом будет проверка в функции которая в зависимости от этого значения будет писать данные в БД.
